const PopularRoles = [
    'Witch',
    'Wizard',
    'Protector',
    'Werewolf',
    'Peasant',
    'Fairy',
    'Archer',
    'Thief',
    'Seer',
    'Ogre',
    'Fighter',
    'Warrior',
    'Soldier',
    'Assassin',
    'Ninja',
    'Mage',
    'Hunter',
    'Ranger',
    'Berserker',
    'Cleric',
    'Priest',
    'Enchanter',
    'Necromancer',
    'Shadowknight',
    'Summoner',
    'Dancer',
    'Bard',
    'Dragoon',
    'Lancer',
    'Blue Mage',
    'Druid'
];

export default PopularRoles;
